### ISSUE TITLE
Add test_connectivity

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/clearpass-api#2]
## Context

Our primary use case is our SOAR app, which expects a `test connectivity` feature.
It makes the most sense to provide that here, in this library.

## Tasks

- [ ] implement test_connectivity (maybe just a call to _get_access_token and validate we got a token?)
- [ ] make test_connectivity return true/false
- [ ] stretch: record a VCR cassette for success
- [ ] stretch: modify a VCR cassette to simulate and test auth failure
